name: medicothink
description: "MedicoThink - AI-Powered Medical Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  
  # Authentication & Security
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.7
  
  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  
  # Audio & Speech
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  audioplayers: ^5.2.1
  record: ^5.0.4
  
  # Connectivity & Utils
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # UI Enhancements
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.10
  
  # Analytics & Crash Reporting
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700